spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jobboard
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-circular-references: true
server:
  error:
    include-message: always


